;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsList]
GameplayTagRedirects=(OldTagName="Abilities|Characters|Basic",NewTagName="Abilities.Characters.Basic")
GameplayTagRedirects=(OldTagName="Abilities",NewTagName="Ability")
GameplayTagRedirects=(OldTagName="Abilities.Knockback",NewTagName="Ability.Knockback")
GameplayTagRedirects=(OldTagName="Abilities.ReceiveKnockback",NewTagName="Ability.ReceiveKnockback")
GameplayTagList=(Tag="Abilities.Characters.Basic",DevComment="")
GameplayTagList=(Tag="Ability",DevComment="")
GameplayTagList=(Tag="Ability.Knockback",DevComment="")
GameplayTagList=(Tag="Ability.ReceiveKnockback",DevComment="")
GameplayTagList=(Tag="Event.Knockback.Apply",DevComment="")
GameplayTagList=(Tag="Event.Knockback.Request",DevComment="")

