;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsList]
GameplayTagRedirects=(OldTagName="Abilities|Characters|Basic",NewTagName="Abilities.Characters.Basic")
GameplayTagList=(Tag="Abilities.Characters.Basic",DevComment="")

